# Big One Dashboard - Cloud Run Deployment

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/big-one-dashboard:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/big-one-dashboard:latest'
      - '.'

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/big-one-dashboard:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'big-one-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/big-one-dashboard:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '100'
      - '--min-instances'
      - '0'

images:
  - 'gcr.io/$PROJECT_ID/big-one-dashboard:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/big-one-dashboard:latest'

timeout: '1200s'
